"""Rewrite Itanium-mangled symbols in LLVM IR (optional MSVC remangling on Windows)."""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ITANIUM_RE = re.compile(r"(_Z[\w\d_@.$]+)")


class CxxfiltNotFoundError(RuntimeError):
    """``c++filt`` is not available on ``PATH``."""


def require_cxxfilt() -> str:
    """Return the ``c++filt`` executable path or raise with ``PATH`` in the message."""
    cxxfilt = shutil.which("c++filt")
    if cxxfilt is None:
        raise CxxfiltNotFoundError(
            "c++filt not found on PATH (required for Itanium demangling).\n"
            f"PATH={os.environ.get('PATH', '')}"
        )
    return cxxfilt


def run_cmd(cmd: list[str], **kwargs) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, **kwargs
    )


def demangle_with_cxxfilt(
    name: str, cxxfilt_bin: str | None = None
) -> tuple[str | None, str | None]:
    proc = run_cmd([cxxfilt_bin or "c++filt", name])
    if proc.returncode != 0:
        return None, proc.stderr
    return proc.stdout.strip(), None


def extract_itanium_symbols(ir_text: str) -> list[str]:
    return sorted(set(ITANIUM_RE.findall(ir_text)))


def try_msvc_mangle(demangled: str, workdir: Path) -> tuple[str | None, str | None]:
    cpp_file = workdir / "stub.cpp"
    src = "// generated by idavator.itanium_to_msvc\n"
    src += "#include <string>\n#include <vector>\n#include <utility>\n\n"
    src += "using namespace std;\n\n"

    sig = demangled
    m = re.search(r"^(.*?::)?([^\s:]+)\((.*)\)$", sig)
    if m:
        qual_name = sig.split("(")[0].strip()
        args = sig[sig.find("(") + 1 : sig.rfind(")")].strip()
        qual_parts = qual_name.split("::")
        func_name = qual_parts[-1]
        namespaces = qual_parts[:-1]
        open_ns = ""
        close_ns = ""
        for ns in namespaces:
            nsid = re.sub(r"[^a-zA-Z0-9_]", "_", ns)
            open_ns += f"namespace {nsid} {{\n"
            close_ns = "}\n" + close_ns
        src += open_ns
        src += f"void {func_name}({args}) {{}}\n"
        src += close_ns
    else:
        src += "int __dummy_symbol_for_mapping() { return 0; }\n"

    cpp_file.write_text(src, encoding="utf-8")

    cl = shutil.which("cl.exe")
    dumpbin = shutil.which("dumpbin.exe")
    if not cl or not dumpbin:
        return None, "MSVC tools (cl.exe or dumpbin.exe) not found in PATH"

    result = run_cmd([cl, "/nologo", "/c", str(cpp_file)], cwd=workdir)
    if result.returncode != 0:
        return None, f"cl.exe failed: {result.stderr.strip() or result.stdout.strip()}"

    objfile = workdir / "stub.obj"
    if not objfile.exists():
        return None, "stub.obj not found after cl.exe"

    db = run_cmd([dumpbin, "/SYMBOLS", str(objfile)], cwd=workdir)
    if db.returncode != 0:
        return None, f"dumpbin failed: {db.stderr.strip() or db.stdout.strip()}"

    symbols = []
    for line in db.stdout.splitlines():
        if "?" in line:
            tok = line.strip().split()[-1]
            if tok.startswith("?") or tok.startswith("??"):
                symbols.append(tok)
    if not symbols:
        return None, "no MSVC-decorated symbols found in dumpbin output"

    return max(symbols, key=len), None


def convert_itanium_to_msvc(
    input_path: str | Path,
    output_path: str | Path,
    *,
    use_msvc: bool = False,
) -> dict[str, dict[str, str | None]]:
    """Convert Itanium symbols in ``input_path`` and write IR + ``.mappings.json``."""
    input_path = Path(input_path)
    output_path = Path(output_path)
    ir_text = input_path.read_text(encoding="utf-8")
    itanium_syms = extract_itanium_symbols(ir_text)

    cxxfilt_bin = require_cxxfilt() if itanium_syms else None

    mappings: dict[str, dict[str, str | None]] = {}
    tmpdir = Path(tempfile.mkdtemp(prefix="itanium2msvc_"))
    try:
        for symbol in itanium_syms:
            demangled, err = demangle_with_cxxfilt(symbol, cxxfilt_bin)
            msvc = None
            msvc_err = err
            if use_msvc and demangled:
                msvc, msvc_err = try_msvc_mangle(demangled, tmpdir)

            mappings[symbol] = {
                "demangled": demangled,
                "msvc_mangled": msvc,
                "msvc_error": msvc_err,
            }

        mappings_file = output_path.with_suffix(".mappings.json")
        mappings_file.write_text(json.dumps(mappings, indent=2), encoding="utf-8")

        out_text = ir_text
        for orig, info in mappings.items():
            if info.get("msvc_mangled"):
                out_text = out_text.replace(orig, info["msvc_mangled"])

        output_path.write_text(out_text, encoding="utf-8")
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)

    return mappings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Convert Itanium mangled symbols in LLVM IR to MSVC-mangled symbols"
    )
    parser.add_argument("input", help="input LLVM IR (.ll)")
    parser.add_argument("output", help="output LLVM IR (.ll) with replacements")
    parser.add_argument(
        "--msvc",
        action="store_true",
        help="attempt MSVC remangling (requires cl.exe/dumpbin.exe on PATH, Windows)",
    )
    args = parser.parse_args(argv)

    try:
        convert_itanium_to_msvc(args.input, args.output, use_msvc=args.msvc)
    except CxxfiltNotFoundError as exc:
        print(exc, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
